### ISSUE TITLE
Error talking to CF

### ISSUE THREAD

**Issue by LynAutumn** [cloudfoundry/stack-auditor#10]
Hey there! 
On PAS 2.3.8 I'm experiencing an error when I run `cf change-stack <appname> cflinuxfs3`, target set to org/space of the particular app. I'm running the command as an admin in a foundation with 180 spaces distributed over 38 orgs. 

> C:\Users\htb7fe\Desktop\stackupgrade>cf change-stack springtest cflinuxfs3
Attempting to change stack to cflinuxfs3 for springtest...
2019/04/24 12:56:38 error talking to cf: application could not be found

When setting CF_TRACE=true, I'm getting below error.

>C:\Users\htb7fe\Desktop\stackupgrade>cf change-stack springtest cflinuxfs3
Attempting to change stack to cflinuxfs3 for springtest...
..//trace stuff..
 2019/04/24 12:48:17 error talking to cf: error unmarshaling spaces json: unexpected end of JSON input

Could this happen due to the amount of spaces as maybe no pagination has been implemented? 

+++++++++++++
**Update**: tested with a standard user whose visibility is restricted to only a few spaces and it's working as expected.

**Comment by dwillist** [comment]
@LynAutumn thanks for the bug report. We are actually already working on this issue and hope to have it resolved shortly

Here is an active issue in our backlog: 
https://www.pivotaltracker.com/story/show/165599492
