### ISSUE TITLE
Wrong processing if the same appname exist on different spaces

### ISSUE THREAD

**Issue by renelehmann** [cloudfoundry/stack-auditor#11]
**Issue:**
The "change-stack" method doesn't take into account that the same appame can exists on different spaces on the same org. It changes the stack only on the first it found. The sort of this list keeps always the same.

**Steps to Reproduce:**
Having two apps with the same name e.g. "lere-static" on different spaces.
It is very common for a developer to have spaces called "dev", "int", "prd" and so on but to have the very same name for the app.

Two apps with the same name (lere-static) on two different spaces in the same org still on stack cflinuxfs2. 
The cf target is set to the second space with guid "e88144..." (see below):

```
cf curl /v3/apps?names=lere-static | egrep "guid|stack"
         "guid": "fdb2aacb-814a-48e9-8206-b26f6492ef6c",
               "stack": "cflinuxfs2"
                  "guid": "691a1bf2-ad90-4d64-a515-5c843abb55c0"
         "guid": "bd4f60e1-1c66-47ba-a6d7-15270320f60b",
               "stack": "cflinuxfs2"
                  "guid": "e88144bb-4481-48ba-ad52-639cc60ce8d1"
```

Changing the stack of appname "lere-static" with the plugin:
```
cf change-stack lere-static cflinuxfs3 --v3
Attempting to change stack to cflinuxfs3 for lere-static...

App lere-static is already started
Application lere-static was successfully changed to Stack cflinuxfs3
``` 

Query again like the integrated method it does:
``` 
cf curl /v3/apps?names=lere-static | egrep "guid|stack"
         "guid": "fdb2aacb-814a-48e9-8206-b26f6492ef6c",
               "stack": "cflinuxfs3"
                  "guid": "691a1bf2-ad90-4d64-a515-5c843abb55c0"
         "guid": "bd4f60e1-1c66-47ba-a6d7-15270320f60b",
               "stack": "cflinuxfs2"
                  "guid": "e88144bb-4481-48ba-ad52-639cc60ce8d1"
``` 

The first app in this list was processed. The app with guid "bd4f..." in the space I am targeted to is sill using cflinuxfs2.

Retry to change the stack in the space I am targeted since the app has still the cflinuxfs2 stack:
```
cf change-stack lere-static cflinuxfs3 --v3
Attempting to change stack to cflinuxfs3 for lere-static...

2019/05/16 08:12:00 error talking to cf: application is already associated with stack cflinuxfs3
``` 

**Expected result:**
The "change-stack" command should change the app in the space I am targeted.
I would like to change the stack on the appname within space "dev" to be sure the new stack works for the same appname also in space "prd".
Right now I don't have a control nor can I fulfill the need to change the stack on all my apps with the same appname.   

Possible solution:
- working with app guid 
- Take only care of the appname within the space I have been targeted.

**Comment by kardolus** [comment]
@renelehmann Thanks for pointing this out! We introduced this bug when we did some performance improvements. Working on fixing it now.

**Comment by kardolus** [comment]
Fixed this on our master branch with [this commit](https://github.com/cloudfoundry/stack-auditor/commit/0b057e4a44b21ffcb7452e386907dfb37f90c096)

We will be releasing this soon (definitely within a week).

@renelehmann Would be great if you could give it a spin though!

**Comment by renelehmann** [comment]
Thanks a lot @kardolus for your fast reply and effort.
I build the stack-auditor (commit 0b057e4a44b21ffcb7452e386907dfb37f90c096) and run into an unexpected error on using the updated plugin.

```
cf change-stack lere-static cflinuxfs3
Attempting to change stack to cflinuxfs3 for lere-static...

lere-static failed to stage on: cflinuxfs3. Restaging on existing stack: cflinuxfs2
```

I then executed the stack change with curl commands (setting the stack_guid) to exclude any problems on the app itself or the platform and it worked with this procedure. 
So I am guessing there is a little regress.

**Comment by kardolus** [comment]
@renelehmann hmmm interesting. I wonder, were you targeting the correct space while you were performing the change-stack command? I mean the space that has the app you want to move to fs3. 

What happened here is that the stack-auditor tried to stage your app on fs3, that failed, and then it busted out and should have left your original app up and running. 

Did you experience any downtime with your app?

Also, could you tell us more about your app? How long does it approximately take to start up? Which buildpack are you using (which language/package manager)? 

Super useful feedback! Thank you so much for giving this a try. Do you happen to have a sample app I could use for reproduction?

**Comment by kardolus** [comment]
^ @shanks3012 interesting stuff right here

**Comment by kardolus** [comment]
@renelehmann just a follow up on this, and the give you some more context, we are implementing a completely new feature. Your app is being staged on fs3 while we just let the fs2 instance run. Then, if your cloud foundry supports it, we will do a zero downtime restart after which your app will be running on fs3. If your CF does not support it, there will be some downtime while your app boots up. 

The advantage here is that if your app does not work well with fs3 (it doesn't compile, or does not start up), then your original app will either keep running (staging fails) or it will be recovered (start up failed).

**Comment by Zanadar** [comment]
@renelehmann Just a quick clarification, did you actually re-stage the app and verify it was working entirely with the curl commands? 
The V3 api allows you to modify the app's stack independently from actually re-staging it and I'm wondering if that's what happened (or if the app got into a funky state somehow). Either way, it would be helpful to see a your curl commands and maybe a sample app.

> I then executed the stack change with curl commands (setting the stack_guid) to exclude any problems on the app itself or the platform and it worked with this procedure.
> So I am guessing there is a little regress.

**Comment by renelehmann** [comment]
@kardolus , @Zanadar Thanks for further informations and questions. 
To clarify, it was or is a simple basic test based on the staticfile_buildback and to reproduce the space issue some developers run or will run into it.

Testcase: push an app based on cflinuxfs2 on two different spaces and migrate the stack
```
  mkdir /tmp/static/;touch /tmp/static/Staticfile
  cf push lere-static -b staticfile_buildpack -s cflinuxfs2 -p /tmp/static
```
 
#Trying the updated stack-auditor plugin "change-stack" with mentioned issues.

Set the stack with API calls (linux formated), successfully (forced with downtime):
```
  cf curl /v2/apps/$APPGUID -d '{"stack_guid":"$STACKGUID"}' -X PUT
  cf curl /v2/apps/$APPGUID -d '{"state":"STOPPED"}' -X PUT
  cf curl /v2/apps/$APPGUID -d '{"state":"STARTED"}' -X PUT
```

Since I know you have implemented the feature for blue/green deployments I checked
our Foundation if all is working as expected. Our cf is align to `cf-deployment 7.11.0`.
The cf implementation fully supports the "rolling app deployment feature" from CAPI (cc_deployment_updater).
But here comes the clue, we do not allow all v3-zdt-* (experimental) calls on our API yet.
Does this now makes sense to the new issue we run?

So, in our case it would be nice if we could have a command option **not** to check or using the "zdt" feature.

**Comment by Zanadar** [comment]
@renelehmann How are you blocking usage of this API? Is there a proxy or something?

**Comment by renelehmann** [comment]
@Zanadar  We call the component `filter` and provides extended endpoints to access the resources which are provided on top of Cloud Foundry (e.g. backup of service_instances). Most of the CC API calls will be forwarded from our LB and gorouter to this component. The filter component then processes the call or forward it over the gorouter to CC.
Since the use of v3-zdt* is not whitelisted yet it will not be forwarded to CC.

**Comment by kardolus** [comment]
@renelehmann thanks for the feedback! We will make it an opt-in functionality to use the v3-zdt-restart command. For example by setting a "--v3" flag.

**Comment by kardolus** [comment]
@renelehmann think we have a nice solution with this commit: https://github.com/cloudfoundry/stack-auditor/commit/2f2211748b5e03495cbd974b0ab7cb8f6301958a

We will release it soon. 

Closing for now, feel free to reopen. Thanks for all the feedback!

**Comment by renelehmann** [comment]
@kardolus Thanks a lot for implementing this nice solution. 
I could successfully test it with or without the "--v3" flag.

(Unfortuantely we block on our `filter` component not only the v3-zdt* but also some "newer" V3 PATCH/POST/PUT/ API calls. So the used `PATCH /v3/apps/:guid/relationships/current_droplet` run into a blockade also. 
But for testing I could use another environment to bypass this behaviour. And we are going to releasing this further blockade soon.)

All good from our side and that you closed it already.
Thanks a lot for your help.
