### ISSUE TITLE
Feature Request: List all apps with their stacks, orgs, and spaces for a certain stack

### ISSUE THREAD

**Issue by macevil** [cloudfoundry/stack-auditor#12]
It would be useful to search for applications that still have a certain stack. Something like:

```bash
>cf audit-stack cflinuxfs2
Retrieving information for all apps...
org1/space1/rz-status cflinuxfs2

>cf audit-stack cflinuxfs3
Retrieving information for all apps...
org1/space1/rubyonrails-hello cflinuxfs3
org1/space1/demo cflinuxfs3
```

**Comment by kardolus** [comment]
@macevil I like this idea, thanks! - will talk it over with the team during our weekly IPM on Monday.

**Comment by kardolus** [comment]
@macevil what is your use case btw? Just out of curiosity; we have a few stories coming up that may help with this. Like export functionality.

**Comment by macevil** [comment]
@kardolus i'm part of a cloud platform team (own datacenter with cloud foundry on premise installation) and we are currently migrating 1500 apps from cflinuxfs2 to cflinuxfs3. and we want to inform the devloper automatically that their apps still uses the old stack.

**Comment by kardolus** [comment]
@macevil ah gotcha. Thanks for the feedback. We have an export function coming up pretty soon. Would it help your team if they had say a json or a csv file with all their apps? Perhaps that is something you could easily perform your own filter on? Making an additional filter doesn't seem like too much work though. Although it's more of a product question. Will discuss with our PM. 

^ @shanks3012

**Comment by macevil** [comment]
@kardolus certainly a structured output would help us -> json preferred

**Comment by shanks3012** [comment]
@macevil I intend to have the tool support both json and csv output formats. I'm going to use your issue here: https://www.pivotaltracker.com/story/show/166151766 as the feature for json export format.

**Comment by emalgamatedsoy** [comment]
There is a way that you would be able to do this by running the following...

Linux : 
cf audit-stack | grep <stack name>

Windows:
cf audit-stack | find "<stack name>"

**Comment by kardolus** [comment]
@macevil version 0.0.5 of stack auditor supports CSV and JSON output.

**Comment by mgibson1121** [comment]
@macevil We currently encourage users to follow the workflow that Guillermo suggests.  Going to close this issue for now, but please comment if you find this approach not feasible.
