### ISSUE TITLE
error talking to cf

### ISSUE THREAD

**Issue by macevil** [cloudfoundry/stack-auditor#13]
hello again, i tried to change a spring application on pws from cflinuxfs2 to 3 with the plugin and get the following error and the application is stopped.

**api endpoint**: https://api.run.pivotal.io
**api version**: 2.134.0
**stack-auditor**: 0.0.3
**cf:** 6.44.0+5de0f0d02.2019-05-01

``` bash
cf change-stack rz-status cflinuxfs3 --v3
Attempting to change stack to cflinuxfs3 for rz-status...

2019/05/21 15:41:47 error talking to cf: App rz-status not found
```
CF_TRACE=true
[trace.log](https://github.com/cloudfoundry/stack-auditor/files/3202848/trace.log)

i've seen the closed issue #10 and the fix with 0.0.3. I'm doing something wrong?

**Comment by kardolus** [comment]
@macevil were you targeting the correct space when you were attempting the change-stack command? I mean the space that has the app called `rz-status`. 

Also note that the next version of stack auditor will support a zero down time restart where as 0.0.3 does not. You can install the version from master if you want to give it a spin (would be super appreciated! :))

**Comment by macevil** [comment]
@kardolus good point!
if i am in the right space, then the stack change works. 👍 
if i'm in the wrong space, the error comes and the app is stopped. 👎 
i will try the master later. 🚀

**Comment by kardolus** [comment]
@macevil yikes, that would be a bug (the app being stopped). I will try and reproduce this.

**Comment by kardolus** [comment]
@macevil this problem is fixed on master :) 

```
Attempting to change stack to cflinuxfs3 for v0fnegtf/otherapp/...

2019/05/22 09:01:46 a problem occurred: no app found with name otherapp
```

Will close this issue, but feel free to reopen if new problems occur. I also added a line to the readme explaining that you have to target the correct space. Thanks for the feedback!
