### ISSUE TITLE
change-stack return "a problem occurred: problem staging new droplet on cflinuxfs3" for any python buildpacks

### ISSUE THREAD

**Issue by JackLue** [cloudfoundry/stack-auditor#14]
Attempting to change stack to cflinuxfs3 for ORG/SPACE/...

2019/06/12 13:38:22 a problem occurred: problem staging new droplet on cflinuxfs3: app build failed. build GUID: 87eb5428-aa47-48c2-b394-92f178ca1226

Tried to use change-stack to change other two python buildpack stack, also failed with similar error message.

**Comment by dwillist** [comment]
@JackLue Hey thanks for opening a github issues. It would be helpful if we could get the output of `cf logs <app_name> --recent` to examine some of the app logs from the attempted restage.

**Comment by JackLue** [comment]
@dwillist Thanks! Found the problem. The app tries to reach out to a retired Artifactory instance to pull dependencies and cannot reach it.

**Comment by Zanadar** [comment]
Closing.
