### ISSUE TITLE
Including build version in CLI itself?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/stack-auditor#15]
This is not something which affects me / not even something that really needs to be changed, but figured I'd point it out:

[The version used in the CLI itself has been "1.0.0"](https://github.com/cloudfoundry/stack-auditor/blob/master/main.go#L146-L150), though the github release has been on incrementing patch versions (0.0.5).

Feel free to close this out anytime 👍

**Comment by mgibson1121** [comment]
Thanks @aegershman, we'll take a look!

**Comment by kardolus** [comment]
@aegershman this was fixed in version 0.0.6.

Feel free to reopen if things are not working correctly! :)
