### ISSUE TITLE
Feature Request: support for custom restart plugin

### ISSUE THREAD

**Issue by naridnevahgar** [cloudfoundry/stack-auditor#17]
Hi, 
Our CF installation doesn't allow ZDT. So, when I try `change-stack` it does a restart with downtime. Would it be possible to accept some existing plugin as argument for the `change-stack` command. Something like below: 

cf change-stack `app name` `stack name` --restart-plugin `plugin name`

I am hoping to use the below plugin for the BG restart. 
https://plugins.cloudfoundry.org/#cf-rolling-restart

Thank you!

**Comment by naridnevahgar** [comment]
I implemented my proposal on local and used rolling restart. But when the instances restart, they fail with a message, download failed. I will check more details, but a first impression is that involving 2 plugins causes conflict to metadata.

**Comment by Zanadar** [comment]
If your PCF doesn't support ZDT, I'm not sure how the plugin would work, because it would likely ha have to use the ZDT API endoints. Have you tried executing `change-stack` with the `--v3`?

**Comment by naridnevahgar** [comment]
Hi @zanader, my pcf capi is 2.1xx and so --v3 says, capi doesn't support zdt. Plugins like rolling restart, do restarts on a per instance basis. Thought for environments where ZDT isn't available, rolling restart would help. 

Update:
I tried doing per instance restart inside `change stack`, restart phase using `cf restart-app-instance`. It didn't help as the CAPI accepts the restart request and the cli quits immediately without waiting for the instance to restart. 

I am thinking about extending one of the bg-restage plugins, to achieve my current task.

**Comment by dfreilich** [comment]
@naridnevahgar Have you had any success with it? I'll close the issue for now, because it doesn't seem like it would help so much, but if you find that it does help, we can keep the feature request in mind for the future.

**Comment by naridnevahgar** [comment]
Hi @dfreilich I managed to extend the bg-restage plugin to do stack change. Thanks for this!
