### ISSUE TITLE
Bug: delete-stack command returns unknown request error

### ISSUE THREAD

**Issue by shauravg** [cloudfoundry/stack-auditor#18]
This is on PWS. At the time of writing this issue, we are on [cf-d 12.1](https://github.com/cloudfoundry/cf-deployment/releases/tag/v12.1.0). 

CLI version: cf version 6.46.1+4934877ec.2019-08-23
stack-auditor 0.0.4

```
 2019-10-16 15:03:23 ⌚ ruby 2.4.2p198 Shauravs-MacBook-Pro in ~
○ → cf delete-stack cflinuxfs2
Are you sure you want to remove the cflinuxfs2 stack? If so, type the name of the stack [cflinuxfs2]
>cflinuxfs2
Deleting stack cflinuxfs2...
2019/10/16 15:03:45 a problem occurred: Unknown request
```

**Comment by dfreilich** [comment]
Thanks for filing, @shauravg ! Stack Auditor isn't our highest priority, so I don't think we'll get to this for a while, but it's definitely something to keep in our backlog and investigate more in the future.

**Comment by ryanmoran** [comment]
@shauravg is this still an issue?

**Comment by ForestEckhardt** [comment]
We're gonna close this as inactive. Please feel free to re-open if you have further issues.
