### ISSUE TITLE
Audit fails when there are more than 5000 apps

### ISSUE THREAD

**Issue by sneal** [cloudfoundry/stack-auditor#21]
Running `cf audit-stack` against a foundation with more than 5000 apps and with CF_TRACE on you see the following output:
```
REQUEST:
GET /https://api.example.com/v3/apps?page=2&per_page=5000 HTTP/1.1
Host: api.example.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
 
RESPONSE:
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 86
Content-Type: application/json;charset=utf-8
Date: Wed, 28 Oct 2020 17:58:53 GMT
Server: nginx
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Vcap-Request-Id: 74f943a4-e7c8-4d0f-4837-bca5161b006a::ab8e29bc-9694-472b-8714-2ad49eadcc33
{
  "description": "Unknown request",
  "error_code": "CF-NotFound",
  "code": 10000
}
```

This is happening because for each subsequent page returned by the v3 API has the full URL to the resource instead of the relative path which the curl command expects.

There are likely other failure cases besides just apps if it's using the v3 API and there are more than 5000 objects. This issue can more easily be reproduced by creating a custom binary and changing [V3ResultsPerPage](https://github.com/cloudfoundry/stack-auditor/blob/e8325ad08467eb753f5a1a1f2efacf7ecb7386f3/cf/cf.go#L22) to something much smaller.

**Comment by Samze** [comment]
This is now fixed, see:
* https://github.com/cloudfoundry/stack-auditor/pull/22
* https://github.com/cloudfoundry/stack-auditor/commit/70bacd03c0cfb59c68ff2c997117955b3b03095c
