### ISSUE TITLE
change-stack returns incorrect information when you do not have space-developer role

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/stack-auditor#5]
The change-stack command returns the following messages when it fails to actually change the stack parameter.

cf change-stack assets cflinuxfs3
App assets is already started

Application assets was successfully changed to Stack cflinuxfs3

This error was actually caused by not having the space-developer role for the application space.

**Comment by Zanadar** [comment]
Thanks for pointing this out! We'll take a look.

**Comment by dwillist** [comment]
Hey thanks for opening a issue [here](https://www.pivotaltracker.com/story/show/163952548) is a link to track this story in our backlog.

**Comment by Zanadar** [comment]
@norman-abramovitz This has been addressed.

Running as a user with `SpaceAudit` role
```
Attempting to change stack to cflinuxfs3 for wat3...

2019/04/03 11:17:52 error talking to cf: The requested URL returned error: 403
```

**Comment by chhhavi** [comment]
This was fixed by including the `--fail` flag during a curl in this commit https://github.com/cloudfoundry/stack-auditor/commit/740a48e8e7b2244e7ab0cece26513ac6fa3d849a
