### ISSUE TITLE
Feature Request: optionally show the current buildpacks

### ISSUE THREAD

**Issue by danlangford** [cloudfoundry/stack-auditor#6]
when upgrading to the latest stack its easy to see that some apps will be able to go easier than others. a lot of this can be determined by knowing the build pack. if the `audit-stack` command had an option to also show the buildpack of each application we could easily begin to identify low hanging fruit (like nginx buildpacks) and others that will require more research and consideration (buildpack is a git url)

**Comment by Zanadar** [comment]
@danlangford Great idea and it shouldn't be too hard (famous last words...) We'll try and get this scheduled soon.

**Comment by Zanadar** [comment]
@danlangford This turns out to be suprisingly complicated given the current data model exposed by the api we talk to. We may get to this down the road, but we're going to table it for now.

cc @kardolus

**Comment by kardolus** [comment]
@danlangford this would require us to do 1 api call per app. 
```
GET /v3/apps/$(cf app appname --guid)/droplets/current
```
That's not doable unfortunately for orgs that have a lot of applications. 

Closing for now. Feel free to reopen.
