### ISSUE TITLE
New github release soon?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/stack-auditor#7]
I'm upgrading to PAS2.5, and part of the release doc suggests using `cf delete-stack cflinuxfs2`. This is a `stack-auditor` plugin command which hasn't been released yet.

Would it be possible to cut a new release of the plugin soon? I'll just build from source in the mean time. Thanks!

- https://github.com/pivotal-cf/docs-pcf-upgrade/blob/master/checklist.html.md.erb#L84
- https://docs.cloudfoundry.org/adminguide/stack-auditor.html#delete-stacks

**Comment by Zanadar** [comment]
@aegershman Yeah we'll be cutting a new release quite soon. Building from source@master should be good to go, but let us know if there are any issues.

**Comment by kardolus** [comment]
@aegershman just cut a release :) 

Feel free to reopen if there are issues

**Comment by aegershman** [comment]
Right on, thanks 👍
