### ISSUE TITLE
change-stack returns incorrect information when you do not have any roles in the space

### ISSUE THREAD

**Issue by cobyrne-pivot** [cloudfoundry/stack-auditor#9]
Similar to #5 , I got the same confusing message. I'm an Org Admin, but didn't have any roles assigned in the space.

When I ran the command it printed out:

```
$ cf change-stack <app> <stack>
Attempting to change stack to <stack> for <app>...

App <app> is already started
Application <app> was successfully changed to Stack <stack>
```

But the stack was not in fact changed. Assigning myself space roles and re-running succeeded, but if I had been paying less attention I wouldn't have known that it hadn't worked the first time.

**Comment by dwillist** [comment]
@cobyrne-pivot Thanks for the bug report. We'll check this out.

**Comment by chhhavi** [comment]
This bug was brought back in this commit: https://github.com/cloudfoundry/stack-auditor/commit/62e30d79014a6f5c89844702b2ce21bd556984f4. If an issue occurs when talking to CAPI through the cf cli, then the cf cli prints out the error as part of a JSON object instead of failing the command.

**Comment by ndon55555** [comment]
Bug addressed in the following story: https://www.pivotaltracker.com/story/show/165024475.
